server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : product-service
          uri: http://localhost:9045
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: http://localhost:9050
          predicates:
            - Path=/cart/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka